- name: Intro to Ansible Playbooks
  hosts: all

  tasks:
  - name: NODEV checking
    ansible.posix.mount:
      src: tmpfs
      path: /dev/shm
      fstype: tmpfs
      opts: defaults,nodev,nosuid,noexec
      state: present

  - name: SELINUX correction
    ansible.builtin.lineinfile:
      path: /etc/selinux/config
      line: SELINUX=permissive
      create: no
      regexp: SELINUX=.*  
  
  - name: Check permissions /etc/issue
    ansible.builtin.file:
      path: /etc/issue
      state: file
      mode: '0644'
      owner: root
      group: root

  - name: Chrony and iptables check installation
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop: "{{ packages }}"
    tags:
      - marek1
      - tomek1

  - name: Crond check enabled
    ansible.builtin.systemd:
      name: crond
      enabled: yes
    tags:
      - marek2

  - name: Sshd config check zmienne
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      line: PermitUserEnvironment no
      create: no
      regexp: PermitUserEnvironment .*
    tags:
      - sshd
    notify:
      - restart_ssh

  - name: Message na starcie
    ansible.builtin.copy:
      src: files/issue
      dest: /etc/issue
      owner: root
      group: root
      mode: '0644'
    tags:
      - mess

  - name: Check permissions /etc/motd
    ansible.builtin.file:
      path: /etc/motd
      state: file
      mode: '0644'
      owner: root
      group: root
    tags:
      - motd

  handlers:
  - name: Restart_ssh
    ansible.builtin.systemd:
      name: sshd
      state: restarted